import type { CanvasWorkspaceEditorProps } from "./canvas-workspace-types";
export type { CanvasWorkspaceEditorProps } from "./canvas-workspace-types";
import { CanvasWorkspaceSurface } from "./graph/CanvasWorkspaceSurface";
import { useCanvasWorkspaceInteractions } from "./use-canvas-workspace-interactions";

/** The public Canvas editor surface; interaction state lives in its dedicated hook. */
export function CanvasWorkspaceEditor({
  artboards,
  focusedArtId,
  onFocusArtboard,
  onBeginMoveArtboard,
  onMoveArtboard,
  onEndMoveArtboard,
  selectedArtId,
  selectedElementIds,
  onSelectionChange,
  onCreateElement,
  onMoveElement,
  onUpdateElement,
  onDeleteElements,
  onRenameArtboard,
  initialCamera,
  initialLayersOpen,
  initialInspectorOpen,
}: CanvasWorkspaceEditorProps) {
  const {
    ordered,
    focused,
    layersOpen,
    setLayersOpen,
    inspectorOpen,
    setInspectorOpen,
    camera,
    workspaceRef,
    selection,
    tool,
    setTool,
    renamingArtId,
    setRenamingArtId,
    drag,
    dragLine,
    rubberbandRect,
    creationOverlayRect,
    overlayRect,
    resizable,
    cancelCreation,
    zoomIn,
    zoomOut,
    resetCamera,
    setSelection,
    beginDrag,
    moveDrag,
    endDrag,
    beginElementDrag,
    updateElementDrag,
    finishElementDrag,
    beginRubberband,
    updateRubberband,
    endRubberband,
    beginWorkspaceInteraction,
    moveWorkspaceInteraction,
    endWorkspaceInteraction,
    cancelWorkspaceInteraction,
    beginCreation,
    moveCreation,
    finishCreation,
    selectAtPoint,
    beginResize,
    handleCanvasKeyDown,
  } = useCanvasWorkspaceInteractions({
    artboards,
    focusedArtId,
    onFocusArtboard,
    onBeginMoveArtboard,
    onMoveArtboard,
    onEndMoveArtboard,
    selectedArtId,
    selectedElementIds,
    onSelectionChange,
    initialCamera,
    onCreateElement,
    onMoveElement,
    onUpdateElement,
    onDeleteElements,
    initialLayersOpen,
    initialInspectorOpen,
  });

  return (
    <CanvasWorkspaceSurface
      ordered={ordered}
      focused={focused}
      layersOpen={layersOpen}
      setLayersOpen={setLayersOpen}
      inspectorOpen={inspectorOpen}
      setInspectorOpen={setInspectorOpen}
      camera={camera}
      workspaceRef={workspaceRef}
      selection={selection}
      tool={tool}
      setTool={setTool}
      onCancelCreation={cancelCreation}
      zoomIn={zoomIn}
      zoomOut={zoomOut}
      resetCamera={resetCamera}
      renamingArtId={renamingArtId}
      setRenamingArtId={setRenamingArtId}
      dragLine={dragLine}
      rubberbandRect={rubberbandRect}
      drag={drag}
      creationOverlayRect={creationOverlayRect}
      overlayRect={overlayRect}
      resizable={resizable}
      onFocusArtboard={onFocusArtboard}
      onUpdateElement={onUpdateElement}
      onMoveElement={onMoveElement}
      onRenameArtboard={onRenameArtboard}
      onSelect={setSelection}
      onBeginDrag={beginDrag}
      onMoveDrag={moveDrag}
      onEndDrag={endDrag}
      onBeginElementDrag={beginElementDrag}
      onUpdateElementDrag={updateElementDrag}
      onFinishElementDrag={finishElementDrag}
      onBeginRubberband={beginRubberband}
      onUpdateRubberband={updateRubberband}
      onEndRubberband={endRubberband}
      onBeginWorkspaceInteraction={beginWorkspaceInteraction}
      onMoveWorkspaceInteraction={moveWorkspaceInteraction}
      onEndWorkspaceInteraction={endWorkspaceInteraction}
      onCancelWorkspaceInteraction={cancelWorkspaceInteraction}
      onBeginCreation={beginCreation}
      onMoveCreation={moveCreation}
      onFinishCreation={finishCreation}
      onSelectAtPoint={selectAtPoint}
      onBeginResize={beginResize}
      onHandleCanvasKeyDown={handleCanvasKeyDown}
    />
  );
}
