// Generated by @mechane/design-system's theme generator. Do not edit by hand.
export const THEME_PALETTE_METADATA = [
  {
    key: "catppuccin",
    label: "Catppuccin",
    primary: "purple",
  },
  {
    key: "gruvbox",
    label: "Gruvbox",
    primary: "orange",
  },
] as const;
