// This file was generated by lezer-generator. You probably shouldn't edit it.
import { LRParser } from "@lezer/lr";
export const parser = LRParser.deserialize({
  version: 14,
  states:
    ")fOVQPOOOOQO'#C`'#C`OOQO'#Cu'#CuOVQPO'#C_OOQO'#Ce'#CeOOQO'#Cf'#CfO!QQPO'#ChO!VQPO'#CiO!^QPO'#CkOOQO'#Cb'#CbOVQPO'#CbO!iQQO'#CaOOQO'#C_'#C_O%ZQQO'#C^QOQPOOOOQO-E6s-E6sOOQO,58y,58yOOQO,59S,59SO%qQPO'#CjOOQO,59T,59TO%|QPO,59TO&RQPO'#CmO&WQPO'#ClOOQO,59V,59VO&`QPO,59VO&eQPO,58|O&jQPO'#CoOVQPO'#CpO&oQPO'#CqO&vQPO'#CrOOQO'#Cn'#CnOOQO'#Cx'#CxO&{QQO,58{OOQO'#Cs'#CsOVQPO'#CyO(lQQO,58xOVQPO'#CtOOQO,58x,58xOVQPO'#CvO)SQPO,59UOOQO1G.o1G.oOVQPO,59XO)_QPO'#CwO)gQPO,59WOOQO1G.q1G.qOOQO1G.h1G.hOOQO,59Z,59ZO)oQPO,59[OOQO,59],59]O)tQPO,59]OOQO,59^,59^OOQO-E6v-E6vOOQO,59e,59eOOQO-E6w-E6wOOQO1G.d1G.dO)yQPO,59`OOQO,59b,59bOOQO-E6t-E6tOOQO1G.s1G.sOOQO,59c,59cOOQO-E6u-E6uOOQO1G.v1G.vOOQO1G.w1G.wOVQPO1G.zOOQO7+$f7+$f",
  stateData:
    "*U~OpOS~OVXOWXOZXOqPOrPOsPOtSOuSOvTOwUOxVO{WO!OYO~OZaO~OzcO~PVOWeOZeO}gO~OwjOxkO!OlO!QmOnTXrTXsTX!RTX!STX!TTX!UTX!VTX!WTX!XTX!YTX!ZTX![TX!]TX!^TX!_TXyTXzTX!PTX|TX}TX~OrqOsqO!RqO!SqO!TqO!UqO!VqO!WqO!XqO!YqO!ZqO![qO!]qO!^qO!_tO~OnQXyQXzQX!PQX|QX}QX~P$YOyvOz^X!P^X~OzxO~O|yO~OyzO}`X~O}|O~O!P}O~OZ!OO~O!P!QO~PVOZ!SO~OwjOxkO!OlO!QmOnTarTasTa!RTa!STa!TTa!UTa!VTa!WTa!XTa!YTa!ZTa![Ta!]Ta!^Ta!_TayTazTa!PTa|Ta}Ta~OnQayQazQa!PQa|Qa}Qa~P$YOyvOz^a!P^a~OWeOZeO~OyzO}`a~Oz!_O~O!P!`O~O|!aO~OtuvZv~",
  goto: "%[nPPo!Y!h!u#UPP#c#cP#c#c#p#c#v#y$P$T$T$T$T$X$]$c$r$x%O%UQ^OSbVlQiYQ!PkQ!XtQ!YvQ![yR!b!ab]OVYkltvy!aR!UrgQORVYklrtvy!ad[OVYklrtvy!aR`RgZORVYklrtvy!agXORVYklrtvy!aQdVR!RlRhWQfWR!]zToZpTnZpTr]sQu]R!WsdROVYklrtvy!aR_RQwbR!ZwQ{fR!^{QpZR!TpQs]R!Vs",
  nodeNames:
    "⚠ Formula Expression PrefixExpression UnaryOperator PostfixExpression PrimaryExpression Number String Boolean Null Identifier Relative Array ArgList Object PropertyList ObjectProperty Postfix Property Index Arguments Pipe BinaryOperator Ternary",
  maxTerm: 61,
  skippedNodes: [0],
  repeatNodeCount: 5,
  tokenData:
    "/a~RuXY#fYZ#f]^#fpq#fqr#wrs$Uuv$svw$xwx%Vxy%oyz%tz{%y{|&O|}&T}!O&Y!O!P&_!P!Q&d!Q![&i![!]'S!^!_'X!_!`'f!`!a'q!a!b(O!c!}(T!}#O(f#P#Q(k#R#S(T#T#Y(T#Y#Z(p#Z#b(T#b#c+Q#c#h(T#h#i,|#i#o(T#o#p.x#p#q.}#q#r/[~#kSp~XY#fYZ#f]^#fpq#fR#|PqP!_!`$PQ$UO!UQ~$XTOr$Urs$hs;'S$U;'S;=`$m<%lO$U~$mOW~~$pP;=`<%l$U~$xO!]~~$}P!^~vw%Q~%VO!S~~%YTOw%Vwx$hx;'S%V;'S;=`%i<%lO%V~%lP;=`<%l%V~%tO!O~~%yO!P~~&OO!Z~~&TOr~~&YOy~~&_Os~~&dOw~~&iO![~~&nQV~!O!P&t!Q![&i~&wP!Q![&z~'PPV~!Q![&z~'XO|~~'^P!X~!_!`'a~'fO!V~~'iP!_!`'l~'qO!T~~'vP!Y~!_!`'y~(OO!W~~(TO!_~~(YSZ~!Q![(T!c!}(T#R#S(T#T#o(T~(kOx~~(pOz~~(uTZ~!Q![(T!c!}(T#R#S(T#T#U)U#U#o(T~)ZUZ~!Q![(T!c!}(T#R#S(T#T#`(T#`#a)m#a#o(T~)rUZ~!Q![(T!c!}(T#R#S(T#T#g(T#g#h*U#h#o(T~*ZUZ~!Q![(T!c!}(T#R#S(T#T#X(T#X#Y*m#Y#o(T~*tSu~Z~!Q![(T!c!}(T#R#S(T#T#o(T~+VUZ~!Q![(T!c!}(T#R#S(T#T#i(T#i#j+i#j#o(T~+nUZ~!Q![(T!c!}(T#R#S(T#T#`(T#`#a,Q#a#o(T~,VUZ~!Q![(T!c!}(T#R#S(T#T#`(T#`#a,i#a#o(T~,pSv~Z~!Q![(T!c!}(T#R#S(T#T#o(T~-RUZ~!Q![(T!c!}(T#R#S(T#T#f(T#f#g-e#g#o(T~-jUZ~!Q![(T!c!}(T#R#S(T#T#i(T#i#j-|#j#o(T~.RUZ~!Q![(T!c!}(T#R#S(T#T#X(T#X#Y.e#Y#o(T~.lSt~Z~!Q![(T!c!}(T#R#S(T#T#o(T~.}O{~~/SP!Q~#p#q/V~/[O!R~~/aO}~",
  tokenizers: [0, 1],
  topRules: { Formula: [0, 1] },
  tokenPrec: 414,
});
