// Generated by scripts/theme-generator.ts.
export const THEME_COLOR_METADATA = [
  {
    key: "red",
    label: "Red",
    order: 0,
    swatchToken: "--palette-red-fill",
  },
  {
    key: "orange",
    label: "Orange",
    order: 1,
    swatchToken: "--palette-orange-fill",
  },
  {
    key: "yellow",
    label: "Yellow",
    order: 2,
    swatchToken: "--palette-yellow-fill",
  },
  {
    key: "green",
    label: "Green",
    order: 3,
    swatchToken: "--palette-green-fill",
  },
  {
    key: "aqua",
    label: "Aqua",
    order: 4,
    swatchToken: "--palette-aqua-fill",
  },
  {
    key: "blue",
    label: "Blue",
    order: 5,
    swatchToken: "--palette-blue-fill",
  },
  {
    key: "purple",
    label: "Purple",
    order: 6,
    swatchToken: "--palette-purple-fill",
  },
] as const;
export type ThemeColorKey = (typeof THEME_COLOR_METADATA)[number]["key"];
