// Renders DiceBear's Line Face style (CC0) without `@dicebear/core` (#796).
//
// The output must stay byte-identical to `@dicebear/core@10.5.0`, minus its
// `<!-- Generated by DiceBear -->` comment and RDF `<metadata>` block, so a
// user's avatar never changes. That means the same PRNG, the same keys and
// the same sort orders as DiceBear's `Prng`, `Resolver` and `Renderer`.
// `avatar-line-face.test.ts` checks this against SVGs DiceBear produced.
//
// Only what Line Face uses is ported: component variant picks, colour picks,
// and per-component rotation. Every other DiceBear option is at its default.
import lineFace from "@dicebear/styles/line-face.json" with { type: "json" };

type AttributeValue = string | { type: string; name: string };

interface StyleElement {
  type: string;
  name: string;
  attributes?: Record<string, AttributeValue>;
  children?: readonly StyleElement[];
}

interface StyleComponent {
  width: number;
  height: number;
  rotate?: { min: number; max: number; step?: number };
  variants: Record<string, { elements: readonly StyleElement[] }>;
}

interface StyleDefinition {
  meta: { source: { name: string } };
  canvas: { width: number; height: number; elements: readonly StyleElement[] };
  attributes: Record<string, string>;
  components: Record<string, StyleComponent>;
  colors: Record<string, { values: readonly string[] }>;
}

const style: StyleDefinition = lineFace;

/** 32-bit FNV-1a over UTF-16 code units (DiceBear `Prng/Fnv1a`). */
function fnv1a(input: string): number {
  let hash = 0x811c9dc5;
  for (let i = 0; i < input.length; i++) {
    hash ^= input.charCodeAt(i);
    hash = Math.imul(hash, 0x01000193);
  }
  return hash >>> 0;
}

/** Mulberry32 returning floats in `[0, 1)` (DiceBear `Prng/Mulberry32`). */
function mulberry32(seed: number): () => number {
  let state = seed;
  return () => {
    state = (state + 0x6d2b79f5) | 0;
    let t = Math.imul(state ^ (state >>> 15), state | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 2 ** 32;
  };
}

/**
 * DiceBear dedupes and sorts before picking or shuffling, so the input order
 * never matters. Its comparator uses `<` on strings, which is the UTF-16
 * code-unit order of the default `sort()`.
 */
function uniqueSorted(items: readonly string[]): string[] {
  return [...new Set(items)].sort();
}

/**
 * Renders the Line Face avatar for `seed` as an SVG document.
 *
 * `backgroundColors` replaces the style's own background palette; entries
 * must be lowercase `#rrggbb`, the form DiceBear normalises colours to before
 * sorting them.
 */
export function lineFaceSvg(seed: string, backgroundColors: readonly string[]): string {
  // DiceBear derives every value from its own `seed:key` stream, so picks
  // are independent of the order they are made in.
  const random = (key: string) => mulberry32(fnv1a(`${seed}:${key}`));
  const hash = fnv1a(`${style.meta.source.name}:${seed}`).toString(16).padStart(8, "0");

  const colors = new Map<string, string>();
  const color = (name: string): string => {
    let picked = colors.get(name);
    if (picked === undefined) {
      const palette = name === "background" ? backgroundColors : (style.colors[name]?.values ?? []);
      // Fisher-Yates over one stream; DiceBear keeps the first colour of the
      // shuffle, which depends on every swap.
      const shuffled = uniqueSorted(palette);
      const next = random(`${name}Color`);
      for (let i = shuffled.length - 1; i > 0; i--) {
        const j = Math.floor(next() * (i + 1));
        // 0 <= j <= i < length, so both reads are in bounds.
        [shuffled[i], shuffled[j]] = [shuffled[j]!, shuffled[i]!];
      }
      picked = shuffled[0] ?? "none";
      colors.set(name, picked);
    }
    return picked;
  };

  const attributes = (attrs: Record<string, AttributeValue> | undefined): string => {
    let out = "";
    for (const [key, value] of Object.entries(attrs ?? {})) {
      out += ` ${key}="${typeof value === "string" ? value : color(value.name)}"`;
    }
    return out;
  };

  const defs: string[] = [];

  const component = (element: StyleElement): string => {
    const definition = style.components[element.name];
    if (!definition) return "";

    const names = uniqueSorted(Object.keys(definition.variants));
    const variant = names[Math.floor(random(`${element.name}Variant`)() * names.length)];
    const elements = variant === undefined ? undefined : definition.variants[variant]?.elements;
    if (!elements) return "";

    const id = `${element.name}-${variant}-${hash}`;
    defs.push(`<g id="${id}">${elements.map(render).join("")}</g>`);

    let attrs = element.attributes;
    const rotate = definition.rotate
      ? rotation(random(`${element.name}Rotate`)(), definition.rotate)
      : 0;
    if (rotate !== 0) {
      const own = attrs?.transform;
      const turn = `rotate(${rotate}, ${definition.width / 2}, ${definition.height / 2})`;
      attrs = { ...attrs, transform: typeof own === "string" && own ? `${own} ${turn}` : turn };
    }
    return `<use${attributes(attrs)} href="#${id}"/>`;
  };

  const render = (element: StyleElement): string => {
    if (element.type === "component") return component(element);
    const children = element.children?.map(render).join("") ?? "";
    const attrs = attributes(element.attributes);
    return children
      ? `<${element.name}${attrs}>${children}</${element.name}>`
      : `<${element.name}${attrs}/>`;
  };

  const { width, height } = style.canvas;
  const background = `<rect width="${width}" height="${height}" fill="${color("background")}"/>`;
  const body = style.canvas.elements.map(render).join("");
  // DiceBear always clips to the border radius, which defaults to 0.
  const clip = `clip-${hash}`;
  defs.push(
    `<clipPath id="${clip}"><rect width="${width}" height="${height}" rx="0" ry="0"/></clipPath>`,
  );

  return (
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}"` +
    `${attributes(style.attributes)} aria-hidden="true">` +
    `<defs>${defs.join("")}</defs>` +
    `<g clip-path="url(#${clip})">${background}${body}</g></svg>`
  );
}

/** A value from a stepped range, rounded like DiceBear's `Prng.float`. */
function rotation(value: number, range: NonNullable<StyleComponent["rotate"]>): number {
  const min = Math.min(range.min, range.max);
  const max = Math.max(range.min, range.max);
  const step = range.step ?? 0;
  const raw =
    step > 0
      ? min + Math.floor(value * (Math.floor((max - min) / step) + 1)) * step
      : min + value * (max - min);
  return Math.round(raw * 10000) / 10000;
}
