/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as GuestRouteRouteImport } from './routes/_guest/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as GuestSignInRouteImport } from './routes/_guest/sign-in'
import { Route as AuthenticatedShowsShowIdRouteImport } from './routes/_authenticated/shows/$showId'
import { Route as AuthenticatedShowsShowIdIndexRouteImport } from './routes/_authenticated/shows/$showId/index'
import { Route as AuthenticatedShowsShowIdArtRouteImport } from './routes/_authenticated/shows/$showId/art'
import { Route as AuthenticatedShowsShowIdArtArtIdRouteImport } from './routes/_authenticated/shows/$showId/art/$artId'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRouteRoute = GuestRouteRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const GuestSignInRoute = GuestSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => GuestRouteRoute,
} as any)
const AuthenticatedShowsShowIdRoute =
  AuthenticatedShowsShowIdRouteImport.update({
    id: '/shows/$showId',
    path: '/shows/$showId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedShowsShowIdIndexRoute =
  AuthenticatedShowsShowIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedShowsShowIdRoute,
  } as any)
const AuthenticatedShowsShowIdArtRoute =
  AuthenticatedShowsShowIdArtRouteImport.update({
    id: '/art',
    path: '/art',
    getParentRoute: () => AuthenticatedShowsShowIdRoute,
  } as any)
const AuthenticatedShowsShowIdArtArtIdRoute =
  AuthenticatedShowsShowIdArtArtIdRouteImport.update({
    id: '/$artId',
    path: '/$artId',
    getParentRoute: () => AuthenticatedShowsShowIdArtRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sign-in': typeof GuestSignInRoute
  '/shows/$showId': typeof AuthenticatedShowsShowIdRouteWithChildren
  '/shows/$showId/art': typeof AuthenticatedShowsShowIdArtRouteWithChildren
  '/shows/$showId/': typeof AuthenticatedShowsShowIdIndexRoute
  '/shows/$showId/art/$artId': typeof AuthenticatedShowsShowIdArtArtIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sign-in': typeof GuestSignInRoute
  '/shows/$showId/art': typeof AuthenticatedShowsShowIdArtRouteWithChildren
  '/shows/$showId': typeof AuthenticatedShowsShowIdIndexRoute
  '/shows/$showId/art/$artId': typeof AuthenticatedShowsShowIdArtArtIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_guest': typeof GuestRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_guest/sign-in': typeof GuestSignInRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/shows/$showId': typeof AuthenticatedShowsShowIdRouteWithChildren
  '/_authenticated/shows/$showId/art': typeof AuthenticatedShowsShowIdArtRouteWithChildren
  '/_authenticated/shows/$showId/': typeof AuthenticatedShowsShowIdIndexRoute
  '/_authenticated/shows/$showId/art/$artId': typeof AuthenticatedShowsShowIdArtArtIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/sign-in'
    | '/shows/$showId'
    | '/shows/$showId/art'
    | '/shows/$showId/'
    | '/shows/$showId/art/$artId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/sign-in'
    | '/shows/$showId/art'
    | '/shows/$showId'
    | '/shows/$showId/art/$artId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_guest'
    | '/_authenticated/settings'
    | '/_guest/sign-in'
    | '/_authenticated/'
    | '/_authenticated/shows/$showId'
    | '/_authenticated/shows/$showId/art'
    | '/_authenticated/shows/$showId/'
    | '/_authenticated/shows/$showId/art/$artId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  GuestRouteRoute: typeof GuestRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_guest/sign-in': {
      id: '/_guest/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof GuestSignInRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_authenticated/shows/$showId': {
      id: '/_authenticated/shows/$showId'
      path: '/shows/$showId'
      fullPath: '/shows/$showId'
      preLoaderRoute: typeof AuthenticatedShowsShowIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shows/$showId/': {
      id: '/_authenticated/shows/$showId/'
      path: '/'
      fullPath: '/shows/$showId/'
      preLoaderRoute: typeof AuthenticatedShowsShowIdIndexRouteImport
      parentRoute: typeof AuthenticatedShowsShowIdRoute
    }
    '/_authenticated/shows/$showId/art': {
      id: '/_authenticated/shows/$showId/art'
      path: '/art'
      fullPath: '/shows/$showId/art'
      preLoaderRoute: typeof AuthenticatedShowsShowIdArtRouteImport
      parentRoute: typeof AuthenticatedShowsShowIdRoute
    }
    '/_authenticated/shows/$showId/art/$artId': {
      id: '/_authenticated/shows/$showId/art/$artId'
      path: '/$artId'
      fullPath: '/shows/$showId/art/$artId'
      preLoaderRoute: typeof AuthenticatedShowsShowIdArtArtIdRouteImport
      parentRoute: typeof AuthenticatedShowsShowIdArtRoute
    }
  }
}

interface AuthenticatedShowsShowIdArtRouteChildren {
  AuthenticatedShowsShowIdArtArtIdRoute: typeof AuthenticatedShowsShowIdArtArtIdRoute
}

const AuthenticatedShowsShowIdArtRouteChildren: AuthenticatedShowsShowIdArtRouteChildren =
  {
    AuthenticatedShowsShowIdArtArtIdRoute:
      AuthenticatedShowsShowIdArtArtIdRoute,
  }

const AuthenticatedShowsShowIdArtRouteWithChildren =
  AuthenticatedShowsShowIdArtRoute._addFileChildren(
    AuthenticatedShowsShowIdArtRouteChildren,
  )

interface AuthenticatedShowsShowIdRouteChildren {
  AuthenticatedShowsShowIdArtRoute: typeof AuthenticatedShowsShowIdArtRouteWithChildren
  AuthenticatedShowsShowIdIndexRoute: typeof AuthenticatedShowsShowIdIndexRoute
}

const AuthenticatedShowsShowIdRouteChildren: AuthenticatedShowsShowIdRouteChildren =
  {
    AuthenticatedShowsShowIdArtRoute:
      AuthenticatedShowsShowIdArtRouteWithChildren,
    AuthenticatedShowsShowIdIndexRoute: AuthenticatedShowsShowIdIndexRoute,
  }

const AuthenticatedShowsShowIdRouteWithChildren =
  AuthenticatedShowsShowIdRoute._addFileChildren(
    AuthenticatedShowsShowIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedShowsShowIdRoute: typeof AuthenticatedShowsShowIdRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedShowsShowIdRoute: AuthenticatedShowsShowIdRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface GuestRouteRouteChildren {
  GuestSignInRoute: typeof GuestSignInRoute
}

const GuestRouteRouteChildren: GuestRouteRouteChildren = {
  GuestSignInRoute: GuestSignInRoute,
}

const GuestRouteRouteWithChildren = GuestRouteRoute._addFileChildren(
  GuestRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  GuestRouteRoute: GuestRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
