/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as GuestRouteRouteImport } from './routes/_guest/route'
import { Route as PrototypeGraphVisualsRouteImport } from './routes/prototype-graph-visuals'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as GuestSignInRouteImport } from './routes/_guest/sign-in'
import { Route as AuthenticatedShowsShowIdRouteImport } from './routes/_authenticated/shows/$showId'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRouteRoute = GuestRouteRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypeGraphVisualsRoute = PrototypeGraphVisualsRouteImport.update({
  id: '/prototype-graph-visuals',
  path: '/prototype-graph-visuals',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const GuestSignInRoute = GuestSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => GuestRouteRoute,
} as any)
const AuthenticatedShowsShowIdRoute =
  AuthenticatedShowsShowIdRouteImport.update({
    id: '/shows/$showId',
    path: '/shows/$showId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/prototype-graph-visuals': typeof PrototypeGraphVisualsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sign-in': typeof GuestSignInRoute
  '/shows/$showId': typeof AuthenticatedShowsShowIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/prototype-graph-visuals': typeof PrototypeGraphVisualsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sign-in': typeof GuestSignInRoute
  '/shows/$showId': typeof AuthenticatedShowsShowIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_guest': typeof GuestRouteRouteWithChildren
  '/prototype-graph-visuals': typeof PrototypeGraphVisualsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_guest/sign-in': typeof GuestSignInRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/shows/$showId': typeof AuthenticatedShowsShowIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/prototype-graph-visuals'
    | '/settings'
    | '/sign-in'
    | '/shows/$showId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/prototype-graph-visuals'
    | '/settings'
    | '/sign-in'
    | '/shows/$showId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_guest'
    | '/prototype-graph-visuals'
    | '/_authenticated/settings'
    | '/_guest/sign-in'
    | '/_authenticated/'
    | '/_authenticated/shows/$showId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  GuestRouteRoute: typeof GuestRouteRouteWithChildren
  PrototypeGraphVisualsRoute: typeof PrototypeGraphVisualsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype-graph-visuals': {
      id: '/prototype-graph-visuals'
      path: '/prototype-graph-visuals'
      fullPath: '/prototype-graph-visuals'
      preLoaderRoute: typeof PrototypeGraphVisualsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_guest/sign-in': {
      id: '/_guest/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof GuestSignInRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_authenticated/shows/$showId': {
      id: '/_authenticated/shows/$showId'
      path: '/shows/$showId'
      fullPath: '/shows/$showId'
      preLoaderRoute: typeof AuthenticatedShowsShowIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedShowsShowIdRoute: typeof AuthenticatedShowsShowIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedShowsShowIdRoute: AuthenticatedShowsShowIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface GuestRouteRouteChildren {
  GuestSignInRoute: typeof GuestSignInRoute
}

const GuestRouteRouteChildren: GuestRouteRouteChildren = {
  GuestSignInRoute: GuestSignInRoute,
}

const GuestRouteRouteWithChildren = GuestRouteRoute._addFileChildren(
  GuestRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  GuestRouteRoute: GuestRouteRouteWithChildren,
  PrototypeGraphVisualsRoute: PrototypeGraphVisualsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
